### PR TITLE
Update class-path.php

### PR DESCRIPTION
**Pull request by johannes85**
Fixed warning for the case, that there isn't a "::" in the include path.

### CODE REVIEW

**Comment by thekid** [comment]
This seems like an awful lot of code to simply handle this situation. When would this occur?

**Comment by johannes85** [comment]
I added a comment to the code.

**Comment by johannes85** [comment]
I made a shorter version

**Comment by thekid** [comment]
+1

**Comment by kiesel** [comment]
:+1:

**Pull request merged**
